import React from 'react';

const Akhi = () => {
    return (
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni mollitia, aliquid iste nesciunt adipisci ullam dolores placeat, veniam at, id enim alias similique. Labore totam minima molestias in sapiente, officiis eum delectus esse sunt iste asperiores quae soluta ipsa, blanditiis incidunt placeat alias id molestiae ipsam aliquam illum nesciunt! Tempore ut fuga omnis autem non dignissimos sunt soluta, nam dolorem unde quo libero totam eos accusantium deleniti tenetur culpa est iure distinctio? Eos numquam ut cum ullam, nesciunt, dignissimos placeat consequatur recusandae odio at natus est velit saepe similique odit veritatis et inventore quo accusantium provident expedita ipsam laudantium? Amet veniam ex minus voluptatum dolores maxime, non neque totam quae quisquam ipsa atque sequi eveniet ab quam repudiandae aspernatur consequatur cupiditate porro dolorem rem. Molestias quis quia, aspernatur nulla repudiandae iste fuga voluptatum sed. Adipisci veniam perferendis dolorum quos? Maiores vel blanditiis consectetur pariatur velit ducimus, quibusdam tenetur amet neque deserunt id recusandae quas! Quia neque, a amet accusamus eos cupiditate cumque error illum laboriosam harum beatae consequuntur velit nisi minus, eius reprehenderit quos exercitationem perferendis architecto nulla quisquam numquam? Cumque laborum unde ex quam! Explicabo eum delectus natus non et odit ea nam repellendus iusto, possimus asperiores cumque officia aut quasi molestiae perspiciatis consequuntur earum molestias quidem, eligendi pariatur? Incidunt voluptas nam alias officiis iusto quo assumenda eligendi voluptates sit atque deleniti omnis vitae quae vero iure, veniam fuga sapiente similique placeat aliquid repudiandae cum minus doloribus corporis! Fugiat, ipsam numquam modi quibusdam repellendus blanditiis fugit harum minima nesciunt sed nobis minus delectus vero sit distinctio architecto impedit saepe neque? Tenetur quidem tempora minus cumque optio quibusdam harum neque facilis obcaecati aliquid aliquam quos culpa autem inventore, fugiat iste repellat. Omnis itaque aliquam libero minus ducimus. Quidem fugit nisi exercitationem quos, eos perspiciatis est in maiores cupiditate. Quo ad eligendi a dolore quibusdam, molestiae rem error aliquid alias quidem, nostrum tempora tempore explicabo doloremque laudantium voluptatem id ullam beatae. Quam, eos accusantium perferendis est hic vitae, illo, saepe sapiente quis dolores cumque tempore asperiores incidunt porro temporibus eligendi at repellendus dolor cupiditate? Quos quaerat officia minima eligendi laborum excepturi? Labore voluptatibus harum vitae rem corrupti itaque provident unde? Aliquid rem voluptate tempore, officiis fugit maiores dolores optio et impedit libero quas molestiae ipsam, a, quos labore tenetur architecto deserunt consequatur vel delectus. Minus, explicabo exercitationem! Nisi modi excepturi soluta veniam consectetur perspiciatis voluptatum neque commodi cumque? Qui, sunt provident.
        </div>
    );
};

export default Akhi;